### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'cpu' 如何解决？

### ISSUE THREAD

**Issue by Bonchi178** [JonnesLin/easy_visualization#1]
if target_class is None:
                target_class = np.argmax(output.cpu().data.numpy())
好像是Evision里生成cam时候报的错，  feature_map, output = self.forward(image),是不是output没有cpu属性？

**Comment by JonnesLin** [comment]
可以提供一下具体的报错信息吗？

**Comment by Bonchi178** [comment]
Traceback (most recent call last):
&nbsp; File "D:/CenterNet_New/centernet_deeplab/Visual_feature_map.py", line 21, in <module&gt;
&nbsp; &nbsp; display.save(image)
&nbsp; File "D:\Andconda3\envs\pytorch\lib\site-packages\Evison\Evison.py", line 110, in save
&nbsp; &nbsp; cam = self.generate_image(image, target_class)
&nbsp; File "D:\Andconda3\envs\pytorch\lib\site-packages\Evison\Evison.py", line 79, in generate_image
&nbsp; &nbsp; target_class = np.argmax(output.cpu().data.numpy())
AttributeError: 'tuple' object has no attribute 'cpu'







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JonnesLin/Evison] AttributeError: &#39;tuple&#39; object has no attribute &#39;cpu&#39; 如何解决？ (Issue #1)





 
可以提供一下具体的报错信息吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JonnesLin** [comment]
icic. 你的网络应该是自己设计的吧？是不是有多个输出？

**Comment by Bonchi178** [comment]
对，MobileNetV2主干的CenterNet，主干部分输出两个尺度特征图，检测头就是原版CenterNet的，输出三个分支




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JonnesLin/Evison] AttributeError: &#39;tuple&#39; object has no attribute &#39;cpu&#39; 如何解决？ (Issue #1)





 
icic. 你的网络应该是自己设计的吧？是不是有多个输出？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JonnesLin** [comment]
有两个解决方案:
    1. 修改library中的源代码，将feature_map, output = self.forward(image) 改成 feature_map, o1, o2, o3 = self.forward(image)，然后取分类的output输入后面的操作
    2. 加载你的模型权重之后，把最好的输出改成只有一个output

**Comment by Bonchi178** [comment]
谢谢您的耐心解答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JonnesLin/Evison] AttributeError: &#39;tuple&#39; object has no attribute &#39;cpu&#39; 如何解决？ (Issue #1)





 
有两个解决方案:
 1. 修改library中的源代码，将feature_map, output = self.forward(image) 改成 feature_map, o1, o2, o3 = self.forward(image)，然后取分类的output输入后面的操作
 2. 加载你的模型权重之后，把最好的输出改成只有一个output
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JonnesLin** [comment]
不客气。我已经更新了代码并且上传到了pip库中，你可以通过设置target_output来制定想要的输出，这样你就不用更改你的代码或者是源码了。I hope it can work :)

**Comment by G-Apple1** [comment]
> 谢谢您的耐心解答
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月29日(星期三) 下午3:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [JonnesLin/Evison] AttributeError: &#39;tuple&#39; object has no attribute &#39;cpu&#39; 如何解决？ (Issue #1) 有两个解决方案: 1. 修改library中的源代码，将feature_map, output = self.forward(image) 改成 feature_map, o1, o2, o3 = self.forward(image)，然后取分类的output输入后面的操作 2. 加载你的模型权重之后，把最好的输出改成只有一个output — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你解决了吗，centernet我还是没搞通哇，help

**Comment by G-Apple1** [comment]
> 不客气。我已经更新了代码并且上传到了pip库中，你可以通过设置target_output来制定想要的输出，这样你就不用更改你的代码或者是源码了。I hope it can work :)

你好，我在centernet还是没跑通，我想知道需要设置哪一层作为输出
