### ISSUE TITLE
您好，该方法可以用在分割网络的特征图上么

### ISSUE THREAD

**Issue by evilvlso** [JonnesLin/easy_visualization#2]
您好，该方法可以用在分割网络的特征图上么

**Comment by JonnesLin** [comment]
如果输出只是mask的话，是不行的。但是如果输出有分类的话(multi-tasks)，就可以使用分类的输出来做。

**Comment by Rui-Zhou-2** [comment]
您好，但是output的size和feature的size不一样怎么办呢～
