### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'cpu' 如何解决？

### ISSUE THREAD

**Issue by HanstBorn** [JonnesLin/easy_visualization#3]
作者你好，在之前的issue里面作者说已解决该问题并已经修改上传至github上，然而并没有，烦请作者更新或者给出问题解决方案。出现的错误信息与前值一致，即：AttributeError: 'tuple' object has no attribute 'cpu' 。

**Comment by JonnesLin** [comment]
Hi,
您好，请问您可以提供更加具体的信息吗？这个问题#1 是因为模型有多个输出，可以通过指定的index来解决。

**Comment by HanstBorn** [comment]
这就一个元组数据向张量的转换问题，想让你改过来方便学生们论文直接使用，作者是在水issue的嫌疑，而不是在解决问题，我的问题很简单，作者在issue2里提及已更新代码解决该问题，然而并没有任何修改。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月06日 04:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [JonnesLin/Evison] AttributeError: 'tuple' object has no attribute 'cpu' 如何解决？ (Issue #3) |

Hi,
您好，请问您可以提供更加具体的信息吗？这个问题#1 是因为模型有多个输出，可以通过指定的index来解决。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YangParky** [comment]
![image](https://user-images.githubusercontent.com/38532963/148323535-62a1f89c-50ec-4e7a-8ffd-42e2b37cb396.png)
![image](https://user-images.githubusercontent.com/38532963/148323589-c91c14f6-7885-4205-b98e-5af89f6e3cb0.png)
当我指定第四层特征层的时候，也是出现同样的问题

**Comment by JonnesLin** [comment]
@HanstBorn 您好，在issue #1 中，存在该问题的原因是因为其模型有多个输出，以至于原本的输出是一个数组。我已经解决这个问题，具体您可以查看8天之前的commit，具体的使用方法也可以查看README.md中的Multi-output。
如果导致这个错误的原因不是这个问题，那么就不能引用issue #1 来解决，所以我提出“请问您可以提供更加具体的信息吗？“

BTW, 我认为我没有在水issue，希望您可以尊重我付出的努力而不是一味地否认，谢谢。

**Comment by JonnesLin** [comment]
@Lature-Yang 请问您可以提供更加具体的信息吗？比如网络的结构，layer4.1输出的数量？

**Comment by YangParky** [comment]
> @Lature-Yang 请问您可以提供更加具体的信息吗？比如网络的结构，layer4.1输出的数量？

您好，我这个layer4.1就是resnet的第四层网络的输出。加载resnet101预训练的模型，然后想可视化一下这层的信息。
![image](https://user-images.githubusercontent.com/38532963/148505251-1a535c72-5adb-40b2-b386-1e8cc40bcd80.png)

**Comment by JonnesLin** [comment]
@Lature-Yang 请问可以提供一下提示的错误信息吗？比如说是源码中具体哪行导致出现问题的？这个是原始的resent101吗？

**Comment by YangParky** [comment]
![image](https://user-images.githubusercontent.com/38532963/148632989-de5154e3-8c6d-410f-961c-6b32c1a9ba96.png)
是原始的resnet101。

**Comment by JonnesLin** [comment]
@Lature-Yang 您好，根据您的信息，我复现了该情况，但是并没有报错出现，具体请看:https://colab.research.google.com/drive/1A9kL-af9hE1E5GAH9kVkbwK9oBZY3Tmj?usp=sharing

**Comment by JonnesLin** [comment]
@Lature-Yang 您可以尝试update最新版本的Evison
